- name: Configure yum package
  ansible.builtin.copy:
    src: redis.repo
    dest: /etc/yum.repos.d/

- name: Install yum
  yum:
    name: redis-6.2.7
    state: installed

- name: Replace 127.0.0.1 with 0.0.0.0
  ansible.builtin.replace:
    path: "{{item}}"
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  loop:
    - /etc/redis.conf
    - /etc/redis/redis.conf

- name: Run tasks from systemd
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd