- name: Configure yum packages
  anisble.builtin.shell: curl -L https://raw.githubusercontent.com/roboshop-devops-project/redis/main/redis.repo -o /etc/yum.repos.d/redis.repo

- name: Install packages
  ansible.builtin.yum:
    name:
      - redis-6.2.11
    state: installed

- name: Update Listen Address in Redis Config
  ansible.builtin.replace:
    path: "{{item}}"
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  loop:
    - /etc/redis.conf
    - /etc/redis/redis.conf

- name: Start Redis
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: yes