#ECHO "Configure Listen Address in MonogBD Configuration"
#sed -i -e 's/127.0.0.1/0.0.0.0/' /etc/mongod.conf
#statusCheck $?
#
#ECHO "Start MongoDB Service"
#systemctl restart mongod &>>${LOG_FILE} && systemctl enable mongod >>${LOG_FILE}
#statusCheck $?
#
#ECHO "Download Schema"
#curl -s -L -o /tmp/mongodb.zip "https://github.com/roboshop-devops-project/mongodb/archive/main.zip"  >>${LOG_FILE}
#statusCheck $?
#
#ECHO "Extract Schema Zip"
#cd /tmp && unzip -o mongodb.zip >>${LOG_FILE}
#statusCheck $?
#
#cd mongodb-main
#ECHO "Load Schema"
#for component in catalogue users ; do
#mongo < ${component}.js >>${LOG_FILE}
#done
##statusCheck $?

- name: Copy mongo repo
  ansible.builtin.file:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install mongodb
  ansible.builtin.yum:
    name: mongodb-org
    state: latest

- name: Replace 127.0.0.1 with 0.0.0.0
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'


