- name: Run tasks from java
  ansible.builtin.import_role:
    name: common
    tasks_from: java

- name: Run tasks from systemd
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd