- hosts: all
  name: play1
  vars_files:
    - sample-vars.yml
  tasks:
    - ansible.builtin.shell: uptime
      register: OUT

    - ansible.builtin.debug:
        msg: "{{ OUTPUT }}"
      vars:
        OUTPUT: "{{ OUT }}"

    - set_fact:
        fact: "{{ OUT.stdout_lines }}"
    - ansible.builtin.debug:
        msg: "{{ fact }}"
