- name: Install
  hosts: "{{HOST_NAME}}"
  become: yes
  tasks:
    - name: lookup secretsmanager secret in the current region
      debug:
        msg: "{{ lookup('aws_secret', 'roboshop',region='us-east-1')}}"


