- name: Run tasks from nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: Run tasks from systemd
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd