- name: Run tasks from python
  ansible.builtin.import_role:
    name: common
    tasks_from: python

- name: Run tasks from systemd
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd