- name: Setup YUM Repos
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

- name: Install RabbitMQ & Erlang
  yum:
    name:
      - https://github.com/rabbitmq/erlang-rpm/releases/download/v23.2.6/erlang-23.2.6-1.el7.x86_64.rpm
      - rabbitmq-server
    state: installed

- name: Run tasks from systemd
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd

- name: create Application user
  community.rabbitmq.rabbitmq_user:
    user: "{{SECRET.RABBITMQ_USER}}"
    password: "{{SECRET.RABBITMQ_PASSWORD}}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
    tags: administrator