- name: Copy mysql repo
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install mysql-community-server
  ansible.builtin.yum:
    name:
      - mysql-community-server
      - MySQL-python
    state: installed

- name: Run tasks from systemd
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd

- name: Get MySQL version with non-default credentials
  community.mysql.mysql_info:
    login_user: root
    login_password: RoboShop@1
    filter: version
  ignore_errors: true
  register: status

- name: status
  when: status.failed | bool
  block:
    - name: Get default password
      ansible.builtin.shell: grep 'A temporary password' /var/log/mysqld.log | awk '{print $NF}'
      register: DEFAULT_PASSWORD

    - name: copy file
      ansible.builtin.copy:
        src: password-reset.sql
        dest: /tmp/password-reset.sql

    - name: change password
      ansible.builtin.shell: mysql --connect-expired-password -u root -p{{DEFAULT_PASSWORD.stdout}} </tmp/password-reset.sql
