- name: Copy mysql repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install mysql-community-server
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed

- name: Run tasks from systemd
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd

- name: Get MySQL version with non-default credentials
  community.mysql.mysql_info:
    login_user: root
    login_password: RoboShop@1
    filter: version
  ignore_errors: true
  register: status

- name: print status
  debug: {{status}}

