- name: Configure NodeJS YUM Repos
  ansible.builtin.shell: curl -fsSL https://rpm.nodesource.com/setup_14.x | bash

- name: Install gcc-c++
  ansible.builtin.yum:
    name:
      - nodejs
      -  gcc-c++
    state: installed

- name: Add the user roboshop
  ansible.builtin.user:
    name: roboshop