- name: Setup Hostname
  ansible.builtin.shell: set-hostname {{COMPONENT}} &
  become: yes

- name: Install multi python packages with version specifiers
  ansible.builtin.pip:
    name:
      - boto3 >= 1.22.0
      - botocore >= 1.25.0
    executable: pip3
