- name: Install gcc-c++
  ansible.builtin.yum:
    name:
      - make
      - gcc-c++
    state: installed

- name: Install Python Modules
  pip:
    name:
      - botocore
      - boto3
    executable: pip3

- name: Configure NodeJS YUM Repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_16.x | sudo -E bash -

- name: Install nodejs
  ansible.builtin.yum:
    name:
      - nodejs
    state: installed

- name: Add the user roboshop
  ansible.builtin.user:
    name: roboshop

- name: Unarchive a file that needs to be downloaded
  ansible.builtin.unarchive:
    src: "https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip"
    dest: /tmp/
    remote_src: yes

- name: Remove file (delete directory)
  ansible.builtin.file:
    path: /home/roboshop/
    state: absent

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}/
    owner: roboshop
    remote_src: yes

- name: Copy server.js file
  ansible.builtin.copy:
    src: "{{COMPONENT}}.js"
    dest: /home/roboshop/{{COMPONENT}}/server.js
    owner: roboshop

- name: Download ca.pem file required to talk to mongodb
  ansible.builtin.get_url:
    url: https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem
    dest: /home/roboshop/{{COMPONENT}}/rds-combined-ca-bundle.pem
  become_user : roboshop

- name: Install  node.js package.
  npm:
    path: /home/roboshop/{{COMPONENT}}/

- name: Install node exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node-exporter


