- name: Copy systemd.service
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service
  notify: handlers

- name: Flush handlers
  meta: flush_handlers

- name: systemd
  ansible.builtin.systemd:
    state: started
    name: "{{COMPONENT}}"
    enabled: true